"use strict";
exports.__esModule = true;
var Secador_1 = require("./Secador");
var SecadorPelo_1 = require("./SecadorPelo");
var SecadorPiso_1 = require("./SecadorPiso");
var secadorComun = new Secador_1["default"]("sony", "2020", 40);
var secadopelo = new SecadorPelo_1["default"]("philips", "2017", 50);
var secadorpiso = new SecadorPiso_1["default"]("panasonic", "2018", 70);
console.log(secadorComun);
console.log(secadorComun.getMarca());
console.log(secadorComun.getModelo());
console.log(secadorComun.getPotencia());
secadorComun.aumentarPotencia();
console.log(secadorComun.getPotencia());
secadorComun.disminuirPotencia();
console.log(secadorComun.getPotencia());
secadorComun.secar(true);
console.log(secadopelo);
console.log(secadopelo.getMarca());
console.log(secadopelo.getModelo());
console.log(secadopelo.getPotencia());
secadopelo.aumentarPotencia();
console.log(secadopelo.getPotencia());
secadopelo.disminuirPotencia();
console.log(secadopelo.getPotencia());
secadopelo.secar(true);
