"use strict";
exports.__esModule = true;
var SmartPhone_1 = require("./SmartPhone");
var motorola = new SmartPhone_1["default"]();
motorola.apagar();
motorola.prender();
motorola.llamar(2494123456);
motorola.sacarFoto();
var lg = new SmartPhone_1["default"]();
lg.apagar();
lg.prender();
lg.llamar(2494674523);
lg.apagar();
lg.sacarFoto();
